<a href="https://colab.research.google.com/github/ashishshaji/EEG_Classification_Deeplearning/blob/master/single_channel_eeg_emotion/eeg_classification_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')


Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [0]:
import pandas as pd
import tensorflow as tf


import numpy as np
import random
random.seed(72)

In [0]:
df=pd.read_csv("/content/gdrive/My Drive/data/emotion1channel.csv")
df

attention  meditation    delta  ...  lowGamma  highGamma  class
0             88          17  1290697  ...      2589       1228      7
1             88          17   105432  ...      2024       1123      7
2             83          29   732143  ...      2362       4157      7
3             80          26    21265  ...      1977       3265      7
4             69          20   349390  ...      9971       6592      7
...          ...         ...      ...  ...       ...        ...    ...
13364         66          61    36288  ...      7245       2287      1
13365         63          81   434483  ...      9214       5527      1
13366         61          91    11198  ...      5412       7044      1
13367         56          88   537338  ...      7453       3461      1
13368         51          90   534966  ...     14293       3204      1

[13369 rows x 11 columns]

In [0]:

df["class"].unique()



array([7, 5, 3, 4, 0, 2, 1, 6])

In [0]:
df.loc[df["class"] == 1, "class"] = 0
df.loc[df["class"] == 2, "class"] = 0
df.loc[df["class"] == 3, "class"] = 0
df.loc[df["class"] == 4, "class"] = 1
df.loc[df["class"] == 5, "class"] = 1
df.loc[df["class"] == 6, "class"] = 1
df.loc[df["class"] == 7, "class"] = 1
df.head()

attention  meditation    delta   theta  ...  highBeta  lowGamma  highGamma  class
0         88          17  1290697   18187  ...      4278      2589       1228      1
1         88          17   105432   21344  ...     12071      2024       1123      1
2         83          29   732143   37527  ...      6050      2362       4157      1
3         80          26    21265   24517  ...      5771      1977       3265      1
4         69          20   349390  145647  ...     19883      9971       6592      1

[5 rows x 11 columns]

In [0]:
x=df.drop(["class","attention","meditation"]  ,axis=1)


In [0]:
y = df.loc[:,'class'].values
print(y)
print(x.values)
x=x.values


[1 1 1 ... 0 0 0]
[[1290697   18187    6345 ...    4278    2589    1228]
 [ 105432   21344    8323 ...   12071    2024    1123]
 [ 732143   37527   48422 ...    6050    2362    4157]
 ...
 [  11198   21200   18905 ...   12856    5412    7044]
 [ 537338   31723    1915 ...    8500    7453    3461]
 [ 534966   54906   30588 ...   17227   14293    3204]]


In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x)
x = scaler.transform(x)
from keras.utils import to_categorical
y = to_categorical(y)
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [0]:
x = np.reshape(x, (x.shape[0],1,x.shape[1]))


In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 155)

In [0]:
"""from tensorflow.keras import Sequential

from tensorflow.keras.layers import Dense, Dropout,BatchNormalization
from tensorflow.keras.layers import Embedding,Dropout
from tensorflow.keras.layers import LSTM
tf.keras.backend.clear_session()


model=Sequential()
model.add(LSTM(128, return_sequences=True,activation="relu",input_shape=(1,8)))  # returns a sequence of vectors of dimension 30
model.add(BatchNormalization())
model.add(Dropout(0.2))
model.add(LSTM(30, return_sequences=True,activation="relu"))
model.add(BatchNormalization())
model.add(LSTM(30, return_sequences=True,activation="relu"))

model.add(Dropout(0.2))  # returns a sequence of vectors of dimension 30
model.add(LSTM(30))  # return a single vector of dimension 30
model.add(Dense(2, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])



model.summary()
model.fit(x_train, y_train, batch_size = 10, epochs = 100, validation_data=(x_test,y_test))
"""

'from tensorflow.keras import Sequential\n\nfrom tensorflow.keras.layers import Dense, Dropout,BatchNormalization\nfrom tensorflow.keras.layers import Embedding,Dropout\nfrom tensorflow.keras.layers import LSTM\ntf.keras.backend.clear_session()\n\n\nmodel=Sequential()\nmodel.add(LSTM(128, return_sequences=True,activation="relu",input_shape=(1,8)))  # returns a sequence of vectors of dimension 30\nmodel.add(BatchNormalization())\nmodel.add(Dropout(0.2))\nmodel.add(LSTM(30, return_sequences=True,activation="relu"))\nmodel.add(BatchNormalization())\nmodel.add(LSTM(30, return_sequences=True,activation="relu"))\n\nmodel.add(Dropout(0.2))  # returns a sequence of vectors of dimension 30\nmodel.add(LSTM(30))  # return a single vector of dimension 30\nmodel.add(Dense(2, activation=\'sigmoid\'))\n\nmodel.compile(loss=\'binary_crossentropy\',\n              optimizer=\'adam\',\n              metrics=[\'accuracy\'])\n\n\n\nmodel.summary()\nmodel.fit(x_train, y_train, batch_size = 10, epochs = 100

In [0]:
import keras
import keras.backend as K
from keras.models import Sequential
from keras.layers import Dense, Activation, LSTM, Dropout, BatchNormalization
model = Sequential()
model.add(LSTM(512, input_shape = (1,8),activation="relu",return_sequences=True))

#model.add(LSTM(100, batch_input_shape = (None, None, x.shape[2])))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(LSTM(256,activation="relu",return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.5))


model.add(LSTM(128,activation="relu",return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.3))

model.add(LSTM(64,activation="relu",return_sequences=True))
model.add(BatchNormalization())
model.add(Dropout(0.3))


model.add(LSTM(32,activation="relu"))
model.add(BatchNormalization())
model.add(Dropout(0.2))



model.add(Dense(700))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(Dropout(0.2))

model.add(Dense(2))
model.add(Activation('sigmoid'))

rmsprop =keras.optimizers.RMSprop(lr=0.009, rho=0.9, epsilon=1e-08)
model.compile(loss='mean_squared_error',
                  optimizer=rmsprop,
                  metrics=['accuracy'])
#adam = keras.optimizers.Adam(lr=0.5, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_24 (LSTM)               (None, 1, 512)            1067008   
_________________________________________________________________
batch_normalization_28 (Batc (None, 1, 512)            2048      
_________________________________________________________________
dropout_28 (Dropout)         (None, 1, 512)            0         
_________________________________________________________________
lstm_25 (LSTM)               (None, 1, 256)            787456    
_________________________________________________________________
batch_normalization_29 (Batc (None, 1, 256)            1024      
_________________________________________________________________
dropout_29 (Dropout)         (None, 1, 256)            0         
_________________________________________________________________
lstm_26 (LSTM)               (None, 1, 128)           

In [0]:
model.fit(x_train, y_train, batch_size = 100, epochs = 100, validation_data=(x_test,y_test))


Train on 10695 samples, validate on 2674 samples
Epoch 1/100
10695/10695 [==============================] - 11s 1ms/step - loss: 0.2240 - accuracy: 0.7020 - val_loss: 0.2114 - val_accuracy: 0.7057
Epoch 2/100
10695/10695 [==============================] - 8s 742us/step - loss: 0.2121 - accuracy: 0.7069 - val_loss: 0.2084 - val_accuracy: 0.7053
Epoch 3/100
10695/10695 [==============================] - 8s 721us/step - loss: 0.2097 - accuracy: 0.7066 - val_loss: 0.2120 - val_accuracy: 0.7057
Epoch 4/100
10695/10695 [==============================] - 8s 723us/step - loss: 0.2114 - accuracy: 0.7025 - val_loss: 0.2109 - val_accuracy: 0.6990
Epoch 5/100
10695/10695 [==============================] - 8s 728us/step - loss: 0.2105 - accuracy: 0.7058 - val_loss: 0.2079 - val_accuracy: 0.7046
Epoch 6/100
10695/10695 [==============================] - 8s 725us/step - loss: 0.2111 - accuracy: 0.7054 - val_loss: 0.2069 - val_accuracy: 0.7057
Epoch 7/100
10695/10695 [==============================] -

In [0]:
from sklearn.metrics import accuracy_score
pred = model.predict(x_test)
predict_classes = np.argmax(pred,axis=1)
expected_classes = np.argmax(y_test,axis=1)
print(expected_classes.shape)
print(predict_classes.shape)
correct = accuracy_score(expected_classes,predict_classes)
print(f"Training Accuracy: {correct}")

(2674,)
(2674,)
Training Accuracy: 0.7030665669409125
